general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 8, y = 8 }
decorations = "full"
opacity = 1.0
startup_mode = "Maximized"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12.0

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "Insert",   mods = "Shift",         action = "Paste" },
  { key = "Insert",   mods = "Control",       action = "Copy" },
]

